### ISSUE TITLE
Exercise 10 unclear

### ISSUE THREAD

**Issue by christianmalek** [fracz/git-exercises#13]
Hi,

git-exercises is awesome. But I don't get what I should do in ex 10. Could you please describe it more specific? Should I change the typo in the commit message or only in the file?

**Comment by fracz** [comment]
You should fix it in both places with `git commit --amend` command.

**Comment by fracz** [comment]
I have added a clarification to [the description](https://github.com/fracz/git-exercises/blob/fix-typo/README.md), thank you!

**Comment by christianmalek** [comment]
This makes it clear. Thanks fracz!
