### ISSUE TITLE
What is the project's license?

### ISSUE THREAD

**Issue by yeputons** [fracz/git-exercises#18]
Currently there is no `LICENSE` file in the repository, one website, or anything. Consequently, it's unclear whether it's permissible to:

1. Fork the project
2. Make modifications to the code and run it
3. Make modifications to the code and do not contribute back
4. Use the website (or self-hosted copy) for education in public institutions
5. Use the website (or self-hosted copy) for education in a for-profit organization

It'd be nice if author's intentions are clearly stated in a license file. I'd personally suggest MIT License or Apache 2 License, they're not copyleft and permit pretty much any usage and modifications without extra liability.

**Comment by fracz** [comment]
Here you go: https://github.com/fracz/git-exercises/commit/d24b73869008a06262099687bb94b477e188c3b1

Thanks!
