### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by vlbrown** [fracz/git-exercises#19]
I've come over from Springboard which recommends your exercises.

First: There needs to be a very large explanation on your home page and FAQ to say "Copy this code into your own terminal windows on your computer". It claims to be "interactive" but it's not.  I've just finished a set of Git Hub exercises at Data Camp -- _they_ are interactive. Yours are copy/paste.

Second: Even after I copied and pasted into my own computer, there is no config.sh file.

```
$ git clone https://gitexercises.fracz.com/git/exercises.git
Cloning into 'exercises'...
remote: Counting objects: 142, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 142 (delta 28), reused 136 (delta 28)
Receiving objects: 100% (142/142), 32.49 KiB | 0 bytes/s, done.
Resolving deltas: 100% (28/28), done.
Checking connectivity... done.
Note: checking out '8da95646b389740e590fc17e9c9547c094efd8a8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

(base) [14:01 Thu Jun 27] ~/Learn/Git
vlb@grimoire 122 $ cd exercises
(base) [14:01 Thu Jun 27] ~/Learn/Git/exercises
vlb@grimoire 123 $ git config user.name "Vicki"
(base) [14:01 Thu Jun 27] ~/Learn/Git/exercises
vlb@grimoire 124 $ git config user.email "vlb@cfcl.com"
(base) [14:01 Thu Jun 27] ~/Learn/Git/exercises
vlb@grimoire 125 $ ./configure.sh
-bash: ./configure.sh: No such file or directory
(base) [14:01 Thu Jun 27] ~/Learn/Git/exercises
vlb@grimoire 126 $ git start
git: 'start' is not a git command. See 'git --help'.

Did you mean one of these?
	stage
	stash
(base) [14:01 Thu Jun 27] ~/Learn/Git/exercises
vlb@grimoire 127 $ l
./		.git/		README.md	start.sh*
../		.gitignore	file.txt
```

**Comment by fracz** [comment]
First: agree, this course is not interactive _in the same way_ as e.g. GitHub tutorial. If you are native, feel free to submit a PR and [edit the welcome text](https://github.com/fracz/git-exercises/blob/verifications/frontend/app/home/home.html#L5).

Second: this looks like a local issue. See that your code checks a commit `8da95646b389740e590fc17e9c9547c094efd8a8` but [there is no such commit in this repo](https://github.com/fracz/git-exercises/search?q=8da95646b389740e590fc17e9c9547c094efd8a8&type=Commits). Are you sure you are cloning the repo to the empty directory?

**Comment by fracz** [comment]
I have checked it myself and indeed, someone managed to break the exercises. The problem should be fixed now - please try removing the `exercises` directory and execute the commands from the home page one more time.

**Comment by javierquirogae** [comment]
I have a similar problem
`Microsoft Windows [Version 10.0.18362.1016]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\javie>cd OneDrive

C:\Users\javie\OneDrive>cd Documents

C:\Users\javie\OneDrive\Documents>cd Springboard

C:\Users\javie\OneDrive\Documents\Springboard>cd GitExercises

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises>git init
Initialized empty Git repository in C:/Users/javie/OneDrive/Documents/Springboard/GitExercises/.git/

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises>git clone https://gitexercises.fracz.com/git/exercises.git
Cloning into 'exercises'...
remote: Counting objects: 141, done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 141 (delta 29), reused 141 (delta 29)
Receiving objects: 100% (141/141), 33.45 KiB | 4.18 MiB/s, done.
Resolving deltas: 100% (29/29), done.

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises>cd exercises

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git config user.name "Javier"

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git config user.email "javierquirogae@gmail.com"

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>./configure.sh
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git start
git: 'start' is not a git command. See 'git --help'.

The most similar commands are
        stage
        stash

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git verify
git: 'verify' is not a git command. See 'git --help'.

The most similar command is
        verify-tag

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git start master
git: 'start' is not a git command. See 'git --help'.

The most similar commands are
        stage
        stash

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>./configure.sh
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git config user.email "javierquirogae@gmail.com"./configure.sh

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git start
git: 'start' is not a git command. See 'git --help'.

The most similar commands are
        stage
        stash

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git start master
git: 'start' is not a git command. See 'git --help'.

The most similar commands are
        stage
        stash

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>git verify
git: 'verify' is not a git command. See 'git --help'.

The most similar command is
        verify-tag

C:\Users\javie\OneDrive\Documents\Springboard\GitExercises\exercises>`

**Comment by fracz** [comment]
@javierquirogae , try using Git Bash instead of Windows CMD.
