### ISSUE TITLE
commit-one-file exercise - files are missing

### ISSUE THREAD

**Issue by vlbrown** [fracz/git-exercises#20]
> Exercise: Commit one file
> git start commit-one-file
> Instructions
> There are two files created in the root project directory - A.txt and B.txt.
> The goal is to commit only one of them.
> 

I don't see these files.

```
$ ls

./		.git/		configure.sh*	test.txt
../		README.md	start.sh*

```

**Comment by fracz** [comment]
The problem should be fixed now, see https://github.com/fracz/git-exercises/issues/19#issuecomment-506625887
