### ISSUE TITLE
Site certificate expired 

### ISSUE THREAD

**Issue by pdias94** [fracz/git-exercises#25]
Hi! I've tried to access the website to continue my progress on the challenge but I've got the invalid SSL screen.

Then I've checked the expiry date of the certificate and notice that it expired yesterday (2020-06-13).

Can you fix it? Thanks!! :)

**Comment by avendesta** [comment]
2 days passed and still not resolved. 😠😠😠😠

**Comment by DaveMinions** [comment]
Same question from me. Is it possible to fix this certificate issue? Thanks. :)

**Comment by fracz** [comment]
Fixed.
