### ISSUE TITLE
Tutorial on how to setup git-exercises locally

### ISSUE THREAD

**Issue by avendesta** [fracz/git-exercises#27]
I see you got a docker folder. I assume that is a way to use the server locally. So would you please make/write a tutorial/instruction on how to set it up locally. 

I really need a local server to verify my works because I'm mostly offline.

Thanks

**Comment by marijnl** [comment]
Same here

**Comment by marijnl** [comment]
I digged into it and found that the source needs compilation and configuration before you can get it to work.
I adapted the code a little and stripped some functionality to make it work:
https://github.com/marijnl/git-exercises 

Use at your own risk

**Comment by fracz** [comment]
Thank you for your tutorial and work! Think I can close this now.
