### ISSUE TITLE
git verify failing

### ISSUE THREAD

**Issue by ComputerFields** [fracz/git-exercises#30]
Hello, I'm getting the  following error with git verify:

```
xxx@xxx MINGW64 ~/git/git-exercises (commit-one-file)
$ git verify
Verifying the commit-one-file exercise. Hold on...
Solution could not be verified - push failed.
Do you have an internet connection?
```

I'm using git bash on Windows 10 Pro.

**Comment by fracz** [comment]
Should be fine now.

**Comment by ComputerFields** [comment]
No change on my end.

I did the following:

- checked out the master branch
- deleted the added files from the workspace (A.txt B.txt)
- deleted the commit-one-file branch
- ./configure.sh
- git start
- git verify

No change, same messages.

**Comment by fracz** [comment]
Try using `git push` instead of the last `git verify` - what is the command output?

**Comment by janez33** [comment]
@ComputerFields I had the same issues but the message saying "Do you have an internet connection?" should be changed with something like "Please take a closer look at the exercise you are probably missing something or check your interner connection"

The solution of this challenge is that you remove one file from the staging area: git remove "B.txt" and then commit with a message: git commit -m "I commited only A.txt" and then: git verify and you are good to go ;)

**Comment by sharjeelsayed** [comment]
I am facing the same issue with "ignore-them" exercise

**Comment by janez33** [comment]
@sharjeelsayed check my answer above yours

**Comment by fracz** [comment]
@janez33 thank you for your input. I have improved detecing of no-progress in a task, so such siutuation should no longer produce "no internet connection" message.
