### ISSUE TITLE
verbatim solution not working for merge-conflict exercise

### ISSUE THREAD

**Issue by michen00** [fracz/git-exercises#37]
Hi, I was using your site to practice and learn git and got as far as the merge-conflict exercise. I couldn't figure this one out, so I tried to Google the solution. I found one and copy-pasted it into my PowerShell terminal and still didn't pass with git verify.

Here is the code I used:

```
git merge another-piece-of-work
echo 2+3=5 > equation.txt
git add equation.txt
git commit --no-edit
```

I  also tried it this way:
```
git merge another-piece-of-work
echo "2 + 3 = 5" > equation.txt
git add equation.txt
git commit --no-edit
```

**Comment by fracz** [comment]
Make sure the `echo` command behaves as expected in PowerShell (the solutions provided in the repository are designed to work in Git Bash).
