### ISSUE TITLE
The chase-branch exercise is not working.

### ISSUE THREAD

**Issue by original-taste** [fracz/git-exercises#42]
I tried to merge escaped to chase-branch but it says "Already up to date."
and then when I try to verify using "git verify", it says 
"You haven't made any progress on exercise chase-branch.
Did you forget to commit your changes?"

**Comment by fracz** [comment]
What does it say when you enter `git status` and `git push`?

**Comment by original-taste** [comment]
I had excluded the file.txt in ".git/info/exclude". so it was excluded from the commit, 
and because of that chase-branch and escaped branch were similar.

thanks for your response.
and sorry for the inconvenience.
