### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mathieutu** [fracz/git-exercises#43]
Hi, just to let you know that I'm a teacher, and I'm in an OSS module with my students.

I found your super website, and exercises, and give them to increase their git skills, and it works like a charm, so a real thank you for your amazing work!

Btw it could be cool (especially for you) to let users delete their "account" when they're done with the exercices. It'll avoid to store useless data for years. 😉

👋

**Comment by fracz** [comment]
No problem. I have also used this platform in classes, with a small addition of gamification. Glad you found it useful.

https://www.researchgate.net/publication/282654230_An_Empirical_Study_Inspecting_the_Benefits_of_Gamification_Applied_to_University_Classes
