### ISSUE TITLE
Problem after cloning the repo

### ISSUE THREAD

**Issue by cod3spac3Academy** [fracz/git-exercises#49]
Hi there, 

I can't solve the exercises after cloning the repo. This problem began a few days ago. 

This is the message that I receive after trying git verify:

Verifying the master exercise. Hold on...
Solution could not be verified - push failed.
Do you have an internet connection?

**Comment by fracz** [comment]
Does the problem still persist?

What is the output if you try simply `git push` ?

**Comment by cod3spac3Academy** [comment]
Hi :smile:
The problem is now solved. The only thing you need to check is the command git start next, it moves the branch to 2 exercises ahead, instead of the next one.
