### ISSUE TITLE
git: 'start' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by iramasauskas** [fracz/git-exercises#50]
I copy how to start part, execute it and get this git: 'start' is not a git command. See 'git --help'.
Seems that git start is not working
![image](https://user-images.githubusercontent.com/114851822/193449086-f7ccd58d-c17d-425b-be9e-44cc943f85ea.png)

**Comment by Bugsbunny1811** [comment]
how you solved this ?

**Comment by Bugsbunny1811** [comment]
same issue for me, can you please help me on this.

**Comment by iramasauskas** [comment]
Please check this thread: https://github.com/orgs/community/discussions/34857#discussioncomment-3781580
