### ISSUE TITLE
Ignore-them exercises not completing

### ISSUE THREAD

**Issue by alespool** [fracz/git-exercises#54]
I use this code to get the exercise done:

![image](https://github.com/fracz/git-exercises/assets/68588737/29c055e4-cfca-4e7d-a5bf-09eafbea1396)

I am only modifying and committing the .gitignore file, and its setup looks fine:

![image](https://github.com/fracz/git-exercises/assets/68588737/ad3ce041-9607-4d15-b50e-37d99ff4717b)

But I get an error for committing 3 files

**Comment by plafrance** [comment]
The line stating "Verifying the commit-one-file-staged" seems to suggest that you are verifying the wrong exercise.

**Comment by fracz** [comment]
Should be working now.
