### ISSUE TITLE
Ignore-them exercise always fails with generated *.exe file

### ISSUE THREAD

**Issue by sferrazzaf** [fracz/git-exercises#9]
```
touch .gitignore
echo >> .gitignore "*"
git add -f .gitignore
git commit -m "Still doesn't work"
git verify
```
Result: FAILED. Blah.exe is not ignored

Also fails with this .gitignore:
```
*.exe
*.jar
*.o
libraries/*
```

Existing example files are ignored by this .gitignore, but the generated blah.txt files always fail.

**Comment by fracz** [comment]
Thank you for letting me know!

Yesterday I ran out of space on the server and a few strange things happened. You should be able to pass this exercise now.

Good luck!

**Comment by arberiii** [comment]
The issue seems still to be valid!

**Comment by martenhernebring** [comment]
This exercise does not ignore .exe files even if I put *.exe in a file named basic.gitignore

**Comment by Nuolong** [comment]
I am running into the same issue here. 
Even after replicating the `.gitignore` file as outlined above, `.exe` files aren't being ignored.

**Comment by fracz** [comment]
Should be ok now

**Comment by mooimcow** [comment]
Hello! I'm still facing this issue as well with the following Fail message:

- Verifying the ignore-them exercise. Hold on...
- Exercise: ignore-them
- Status: FAILED
- KNa0mgfq.exe file is not ignored

Thank you!

**Comment by TeodoraCerevicki** [comment]
I'm getting 
Status: FAILED
libraries directory is not ignored

and my code is:
*.exe
*.jar
*.o
libraries/*

**Comment by fracz** [comment]
Are you sure you wrote the rules in the `.gitignore` file and committed it?

**Comment by TeodoraCerevicki** [comment]
yup :/

**Comment by steffenschneider** [comment]
same problem here

**Comment by nagarajareddy** [comment]
Getting Same error that libraries directory is not ignored 
Seems there is open issue on the ignore-them branch here in #41

**Comment by jkalandarov** [comment]
In `.gitignore`:
```
*.exe
*.o
*.jar
libraries/
```
extension files ignored but not a folder. tried different combinations still failed.

The issue stands still

**Comment by rodolso** [comment]
Hi! I'm getting the same issue:

```
git verify
Verifying the ignore-them exercise. Hold on...  
Exercise: ignore-them  
Status: FAILED  
F2nwA8o0.exe file is not ignored
```

Thank you!

**Comment by fracz** [comment]
That means that your `.gitignore` file would not ignore such file (this is a verification mechanism). Are you sure your `.gitignore` file is committed?

**Comment by rodolso** [comment]
`.gitignore` was committed when I got the "Failed" status 2 days ago.
I've tried a different procedure and can confirm that the verification mechanism works like a charm, the mistake was mine.
Looks like the problem was due to a `.txt` extension on the `.gitignore` file.

Dziękuję @fracz for your support and for the exercises!
